import logging
from agents.narrator_agent import NarratorAgent
from agents.dice_roller_agent import DiceRollerAgent
from agents.npc_agent import NPCInteractionAgent
from agents.memory_agent import MemoryAgent
from classifier import MessageClassifier

# Set up basic logging.
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class AgentRegistry:
    """
    Registry to maintain and provide access to available agents.
    """
    def __init__(self, memory_agent: MemoryAgent):
        self.agents = {
            "narrative": NarratorAgent(memory_agent=memory_agent),
            "dice": DiceRollerAgent(memory_agent=memory_agent),
            "npc": NPCInteractionAgent(memory_agent=memory_agent)
        }

    def get_agent(self, agent_type: str):
        return self.agents.get(agent_type, None)

class Orchestrator:
    def __init__(self):
        self.memory_agent = MemoryAgent()
        self.agent_registry = AgentRegistry(self.memory_agent)
        self.classifier = MessageClassifier()

    def process_message(self, message: str) -> str:
        """
        Process the incoming user message:
          1. Use the classifier to choose an agent.
          2. Retrieve conversation context from memory.
          3. Call the appropriate agent to handle the message.
          4. Return the agent's response.
        """
        logger.info("Processing message: %s", message)
        agent_type = self.classifier.classify(message)
        logger.info("Message classified as: %s", agent_type)
        agent = self.agent_registry.get_agent(agent_type)
        if agent is None:
            return "No agent available to process your message."

        # Gather context from each thread of conversation.
        context = {
            "narrative": self.memory_agent.summarize_memory("narrative"),
            "dice": self.memory_agent.summarize_memory("dice"),
            "npc": self.memory_agent.summarize_memory("npc")
        }

        response = agent.handle_message(message, context)
        logger.info("Response generated by %s agent", agent.name)
        return response
